/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdio.h>

/*Some Macro definitions*/

//ARM Cortex-M4 processor has 2 SRAM. Size of the combined SRAM is 128 K_Byte.
#define SRAM_START    0x20000000U   //Defining the STARTING address of SRAM
#define SRAM_SIZE     (128 * 1024)  //In byte.
#define SRAM_END      (SRAM_START + SRAM_SIZE)  // End address of the SRAM
#define STACK_START   SRAM_END      // STACK starts from SRAM end because in ARM Cortex-M4 stack operates in "Full Descending" manner.

//Here we are creating STACK memory of 1 K_Byte. In which MSP can access 512 Bytes and PSP can also access another 512 Bytes.
#define STACK_MSP_START  SRAM_END
#define STACK_MSP_END   (STACK_MSP_START - 512)
#define STACK_PSP_START  STACK_MSP_END
#define STACK_PSP_END   (STACK_PSP_START - 512)

int add_fun(int a, int b, int c, int d)
{
	return (a+b+c+d);
}

//This is a naked function. We can write 'INLINE ASSEMBLY' instruction inside this function.
__attribute__((naked)) void change_sp_to_psp()
{
	//This are ASSEMBLY style MACRO behaves same as 'C' MACRO.
	__asm volatile(".equ SRAM_END, (0x20000000 + (128 * 1024))");
	__asm volatile(".equ PSP_START, (SRAM_END - 512)");
	__asm volatile(".equ PSP_END, (PSP_START - 512)");

	//Initialized PSP register with some valid STACK address or location.
	__asm volatile("LDR R0, =PSP_START");
	__asm volatile("MSR PSP, R0");

	//Enabling PSP as Current Stack Pointer by setting(1) SPSEL bit of the CONTROL register.
	__asm volatile("MOV R0, #0x02");
	__asm volatile("MSR CONTROL, R0");

	//After completing all the above instructions return to the main() function.
	__asm volatile("BX LR");
}

void generate_exception()
{
	__asm volatile("SVC #0x02");
}

int main(void)
{
	change_sp_to_psp();

    int result;
    result = add_fun(1, 4, 5, 6);
    printf("Result = %d\n", result);

    generate_exception();

    for(;;);
}

void SVC_Handler()
{
	printf("In SVC_Handler\n");
}
