/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

int calle_function(int a, int b)
{
	return (a+b);
}
void print_function(void)
{
	printf("Hello World!!\n");
}
int main(void)
{
	int A = 15, B = 35;

	void (*func_ptr)(void);
	func_ptr = print_function;
	func_ptr();

	int result = calle_function(A,B);



	for(;;);
}
