/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include <stdint.h>

int main(void)
{
#if 0
	__asm volatile("LDR R1,=#0X20001000");
	__asm volatile("LDR R2,=#0X20001004");
    __asm volatile("LDR R0,[R1]");
    __asm volatile("LDR R1,[R2]");
    __asm volatile("ADD R0,R0,R1");
    __asm volatile("STR R0,[R2]");
#endif

    //Input Operand
    int val = 50;
    __asm volatile("MOV R0,%0"::"r"(val));

    //Output Operand
    uint32_t control_reg;
    __asm volatile("MRS %0,CONTROL":"=r"(control_reg));

    //Copy the content of 'C' variable "var1 to var2"
    int var1 = 10, var2;
    __asm volatile("MOV %0,%1":"=r"(var2):"r"(var1));

    //Copy the content of a pointer to another variable
    int p1, *p2;
    p2 = (int*) 0X20000008;
    __asm volatile("LDR %0,[%1]":"=r"(p1):"r"(p2));
    for(;;);
}
