/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include<stdint.h>


int main(void)
{
    uint32_t volatile *pClkctrlReg   =(uint32_t*) 0x40023830;
    uint32_t volatile *pPortDModeReg =(uint32_t*) 0x40020C00;
    uint32_t volatile *pPortDOutReg  =(uint32_t*) 0x40020C14;

    uint32_t volatile *pPortAModeReg =(uint32_t*) 0x40020000;
    uint32_t volatile *pPortAInReg   =(uint32_t*) 0x40020010;

    //1. Enable the clock of GPIOD, GPIOA peripheral in the AHB1ENR.
    *pClkctrlReg |= (0x1<<3);
    *pClkctrlReg |= (0x1<<0);

    //2. Configuring PD12 as OUTPUT mode(GPIOD MODE REGISTER).
    *pPortDModeReg &= ~(0x3<<24); //Clearing the 24th and 25th bit.
    *pPortDModeReg |= (0x1<<24);  //Setting the 24th bit.

    //2.1 Configuring PA0 as INPUT mode (GPIOA MODE REGISTER).
    *pPortAModeReg &= ~(0x3<<0);

    while(1){

		//3. Read the pin status of pin PA0 (GPIOA INPUT DATA REGISTER).
		uint8_t pinStatus = (uint8_t) (*pPortAInReg & 0x1);  // Zero out all bits except bit 0.

		if(pinStatus){
			//Turn on the LED.
			*pPortDOutReg |= (0x1 << 12);
		}else{
			//Turn off the LED.
			*pPortDOutReg &= ~(0x1 << 12);
		}
    }

}
