/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "EmbeddedStruct.h"


int main(void){

    RCC_AHB1ENR_t volatile *const pClkCtrlReg   = (RCC_AHB1ENR_t*) 0x40023830;
    GPIOx_MODER_t volatile *const pPortDModeReg = (GPIOx_MODER_t*) 0x40020C00;
    GPIOx_ODR_t   volatile *const pPortDOutReg  = (GPIOx_ODR_t*) 0x40020C14;

    pClkCtrlReg->gpioD_en = 0x1;
    pPortDModeReg->pin_12 = 0x1;

    while(1){
        pPortDOutReg->pin_12 = 0x1;

        for(uint32_t i = 0; i < 100000; i++);

        pPortDOutReg->pin_12 = 0x0;

        for(uint32_t i = 0; i < 100000; i++);
    }
}
