/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

#define IRQNO_TIMER2  28
#define IRQNO_I2C1    31

uint32_t *pNVIC_ISER_base = (uint32_t*) 0xE000E100;
uint32_t *pNVIC_ISPR_base = (uint32_t*) 0XE000E200;
uint32_t *pNVIC_IPR_base  = (uint32_t*) 0xE000E400;

void configure_priority_for_IRQs(uint8_t irq_no, uint8_t priority_value)
{
	//1. Find out IPRx.
	uint8_t IPRx = irq_no/4;

	//2. Address of the IPRx.
	uint32_t *IPR = (pNVIC_IPR_base + IPRx);

	//3. Position in IPRx.
	uint8_t pos = ( (irq_no % 4) * 8);

	//4. Configure the priority.
	*IPR &= ~(0xFF << pos); //1st clear the priority.
	*IPR |=  (priority_value << pos); // 2nd Set the priority
}

int main(void)
{
    //1st Configure the priority for the peripherals.
	configure_priority_for_IRQs(IRQNO_TIMER2, 0x80);
	configure_priority_for_IRQs(IRQNO_I2C1, 0x70);

	//2nd Enable the IRQ in NVIC ISER.
	*pNVIC_ISER_base |= (1 << IRQNO_TIMER2);
	*pNVIC_ISER_base |= (1 << IRQNO_I2C1);

	//3rd Set the interrupt pending bit in the NVIC PR.
	*pNVIC_ISPR_base |= (1 << IRQNO_TIMER2);

	//Print out some scrap.
	printf("Printing out some scrap after both interrupt execution.\n");

	for(;;);

}

//ISRs
void TIM2_IRQHandler(void)
{
	printf("[TIM2_IRQHandler]\n");
	*pNVIC_ISPR_base |= (1 << IRQNO_I2C1);
	printf("printing after I2C1_EV_IRQHandler call\n");
}

void I2C1_EV_IRQHandler(void)
{
	printf("[I2C1_EV_IRQHandler]\n");
}
