/*
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

RCC_AHB1ENR_t volatile *const pClkCtrlReg   = (RCC_AHB1ENR_t*) 0x40023830;
GPIOx_MODER_t volatile *const pPortDModeReg = (GPIOx_MODER_t*) 0x40020C00;
GPIOx_ODR_t   volatile *const pPortDOutReg  = (GPIOx_ODR_t*)   0x40020C14;

void RVS_seq();
void FWD_seq();
void top_to_bottom();
void side_seq();

void delay(void){

	for(uint32_t i = 0 ; i < 100000 ; i++);
}

int main(void)
{

	/* 1. Enabling GPIOD by enabling clock */
	pClkCtrlReg->gpioD_en = 0X01;

	//2. Enabling PD0,PD1,PD2,PD3,PD8,PD9,PD10,PD11 as output mode.
	pPortDModeReg->pin_0  = 0X01;  // PD0 as R0
	pPortDModeReg->pin_1  = 0X01;  // PD1 as R1
	pPortDModeReg->pin_2  = 0X01;  // PD2 as R2
	pPortDModeReg->pin_3  = 0X01;  // PD3 as R3

	pPortDModeReg->pin_8  = 0X01;   // PD8  as C0
	pPortDModeReg->pin_9  = 0X01;   // PD9  as C1
	pPortDModeReg->pin_10 = 0X01;   // PD10 as C2
	pPortDModeReg->pin_11 = 0X01;   // PD11 as C3


	//3. Set PD0 to PD3 LOW and PD8 to PD11 HIGH.
	pPortDOutReg->pin_0  = 0X00;  //R0 - PD0
	pPortDOutReg->pin_1  = 0X00;  //R1 - PD1
	pPortDOutReg->pin_2  = 0X00;  //R2 - PD2
	pPortDOutReg->pin_3  = 0X00;  //R3 - PD3

	pPortDOutReg->pin_8  = 0X01;  //C0 - PD8
	pPortDOutReg->pin_9  = 0X01;  //C1 - PD9
	pPortDOutReg->pin_10 = 0X01;  //C2 - PD10
	pPortDOutReg->pin_11 = 0X01;  //C3 - PD11

	uint8_t count1 = 0;
	while(1){
		count1 = 0;
		while(count1 <= 2){

			FWD_seq();
			RVS_seq();
			count1++;
		}
		top_to_bottom();
		side_seq();
	}
}

void FWD_seq(){

				/*Row 0*/
			pPortDOutReg->pin_0  = 0X01;  //R0 HIGH

			pPortDOutReg->pin_8  = 0X00;  //C0 LOW
			delay();
			pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
			delay();
			pPortDOutReg->pin_9  = 0X00;  //C1 LOW
			delay();
			pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
			delay();
			pPortDOutReg->pin_10 = 0X00;  //C2 LOW
			delay();
			pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
			delay();
			pPortDOutReg->pin_11 = 0X00;  //C3 LOW
			delay();
			pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
			delay();
			pPortDOutReg->pin_0  = 0X00;  //R0 LOW
				/*Row 1*/
			pPortDOutReg->pin_1  = 0X01;  //R1 HIGH

			pPortDOutReg->pin_11 = 0X00;  //C3 LOW
			delay();
			pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
			delay();
			pPortDOutReg->pin_10 = 0X00;  //C2 LOW
			delay();
			pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
			delay();
			pPortDOutReg->pin_9  = 0X00;  //C1 LOW
			delay();
			pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
			delay();
			pPortDOutReg->pin_8  = 0X00;  //C0 LOW
			delay();
			pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
			delay();
			pPortDOutReg->pin_1  = 0X00;  //R1 LOW
				/*Row 2*/
			pPortDOutReg->pin_2  = 0X01;  //R2 HIGH

			pPortDOutReg->pin_8  = 0X00;  //C0 LOW
			delay();
			pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
			delay();
			pPortDOutReg->pin_9  = 0X00;  //C1 LOW
			delay();
			pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
			delay();
			pPortDOutReg->pin_10 = 0X00;  //C2 LOW
			delay();
			pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
			delay();
			pPortDOutReg->pin_11 = 0X00;  //C3 LOW
			delay();
			pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
			delay();
			pPortDOutReg->pin_2  = 0X00;  //R2 LOW
				/*Row 3*/
			pPortDOutReg->pin_3  = 0X01;  //R3 HIGH

			pPortDOutReg->pin_11 = 0X00;  //C3 LOW
			delay();
			pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
			delay();
			pPortDOutReg->pin_10 = 0X00;  //C2 LOW
			delay();
			pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
			delay();
			pPortDOutReg->pin_9  = 0X00;  //C1 LOW
			delay();
			pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
			delay();
			pPortDOutReg->pin_8  = 0X00;  //C0 LOW
			delay();
			pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
			delay();
			pPortDOutReg->pin_3  = 0X00;  //R3 LOW


}

void RVS_seq(){

		/*Row 3*/
		pPortDOutReg->pin_3  = 0X01;  //R3 HIGH

		pPortDOutReg->pin_8  = 0X00;  //C0 LOW
		delay();
		pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
		delay();
		pPortDOutReg->pin_9  = 0X00;  //C1 LOW
		delay();
		pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
		delay();
		pPortDOutReg->pin_10 = 0X00;  //C2 LOW
		delay();
		pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
		delay();
		pPortDOutReg->pin_11 = 0X00;  //C3 LOW
		delay();
		pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
		delay();
		pPortDOutReg->pin_3  = 0X00;  //R3 LOW
			/*Row 2*/
		pPortDOutReg->pin_2  = 0X01;  //R2 HIGH

		pPortDOutReg->pin_11 = 0X00;  //C3 LOW
		delay();
		pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
		delay();
		pPortDOutReg->pin_10 = 0X00;  //C2 LOW
		delay();
		pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
		delay();
		pPortDOutReg->pin_9  = 0X00;  //C1 LOW
		delay();
		pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
		delay();
		pPortDOutReg->pin_8  = 0X00;  //C0 LOW
		delay();
		pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
		delay();
		pPortDOutReg->pin_2  = 0X00;  //R2 LOW
			/*Row 1*/
		pPortDOutReg->pin_1  = 0X01;  //R1 HIGH

		pPortDOutReg->pin_8  = 0X00;  //C0 LOW
		delay();
		pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
		delay();
		pPortDOutReg->pin_9  = 0X00;  //C1 LOW
		delay();
		pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
		delay();
		pPortDOutReg->pin_10 = 0X00;  //C2 LOW
		delay();
		pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
		delay();
		pPortDOutReg->pin_11 = 0X00;  //C3 LOW
		delay();
		pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
		delay();
		pPortDOutReg->pin_1  = 0X00;  //R1 LOW
			/*Row 0*/
		pPortDOutReg->pin_0  = 0X01;  //R0 HIGH

		pPortDOutReg->pin_11 = 0X00;  //C3 LOW
		delay();
		pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
		delay();
		pPortDOutReg->pin_10 = 0X00;  //C2 LOW
		delay();
		pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
		delay();
		pPortDOutReg->pin_9  = 0X00;  //C1 LOW
		delay();
		pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
		delay();
		pPortDOutReg->pin_8  = 0X00;  //C0 LOW
		delay();
		pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
		delay();
		pPortDOutReg->pin_0  = 0X00;  //R0 LOW

}

void top_to_bottom(){
	uint8_t count = 0;
	pPortDOutReg->pin_8  = 0X00;  //C0 LOW
	pPortDOutReg->pin_9  = 0X00;  //C1 LOW
	pPortDOutReg->pin_10 = 0X00;  //C2 LOW
	pPortDOutReg->pin_11 = 0X00;  //C3 LOW

	while(count <= 5){
		/*Down*/
		pPortDOutReg->pin_0  = 0X01;  //R0 HIGH
		delay();
		pPortDOutReg->pin_0  = 0X00;  //R0 LOW
		delay();
		pPortDOutReg->pin_1  = 0X01;  //R1 HIGH
		delay();
		pPortDOutReg->pin_1  = 0X00;  //R1 LOW
		delay();
		pPortDOutReg->pin_2  = 0X01;  //R2 HIGH
		delay();
		pPortDOutReg->pin_2  = 0X00;  //R2 LOW
		delay();
		pPortDOutReg->pin_3  = 0X01;  //R3 HIGH
		delay();
		pPortDOutReg->pin_3  = 0X00;  //R3 LOW
		delay();
		/*Up*/
		pPortDOutReg->pin_3  = 0X01;  //R3 HIGH
		delay();
		pPortDOutReg->pin_3  = 0X00;  //R3 LOW
		delay();
		pPortDOutReg->pin_2  = 0X01;  //R2 HIGH
		delay();
		pPortDOutReg->pin_2  = 0X00;  //R2 LOW
		delay();
		pPortDOutReg->pin_1  = 0X01;  //R1 HIGH
		delay();
		pPortDOutReg->pin_1  = 0X00;  //R1 LOW
		delay();
		pPortDOutReg->pin_0  = 0X01;  //R0 HIGH
		delay();
		pPortDOutReg->pin_0  = 0X00;  //R0 LOW
		delay();
		count++;
	}

	pPortDOutReg->pin_8  = 0X01;  //C0 HIGH
	pPortDOutReg->pin_9  = 0X01;  //C1 HIGH
	pPortDOutReg->pin_10 = 0X01;  //C2 HIGH
	pPortDOutReg->pin_11 = 0X01;  //C3 HIGH
}

void side_seq(){
	uint8_t count2 = 0;
	pPortDOutReg->pin_0  = 0X01;  //R0 HIGH
	pPortDOutReg->pin_1  = 0X01;  //R1 HIGH
	pPortDOutReg->pin_2  = 0X01;  //R2 HIGH
	pPortDOutReg->pin_3  = 0X01;  //R3 HIGH

	while(count2 <= 5){
		/*Left to Right*/
		pPortDOutReg->pin_8   = 0X00;  //C0 LOW
		delay();
		pPortDOutReg->pin_8   = 0X01;  //C0 HIGH
		delay();
		pPortDOutReg->pin_9   = 0X00;  //C1 LOW
		delay();
		pPortDOutReg->pin_9   = 0X01;  //C1 HIGH
		delay();
		pPortDOutReg->pin_10  = 0X00;  //C2 LOW
		delay();
		pPortDOutReg->pin_10  = 0X01;  //C2 HIGH
		delay();
		pPortDOutReg->pin_11  = 0X00;  //C3 LOW
		delay();
		pPortDOutReg->pin_11  = 0X01;  //C3 HIGH
		delay();
		/*Right to Left*/
		pPortDOutReg->pin_11  = 0X00;  //C3 LOW
		delay();
		pPortDOutReg->pin_11  = 0X01;  //C3 HIGH
		delay();
		pPortDOutReg->pin_10  = 0X00;  //C2 LOW
		delay();
		pPortDOutReg->pin_10  = 0X01;  //C2 HIGH
		delay();
		pPortDOutReg->pin_9   = 0X00;  //C1 LOW
		delay();
		pPortDOutReg->pin_9   = 0X01;  //C1 HIGH
		delay();
		pPortDOutReg->pin_8   = 0X00;  //C0 LOW
		delay();
		pPortDOutReg->pin_8   = 0X01;  //C0 HIGH
		delay();
		count2++;
	}

	pPortDOutReg->pin_0  = 0X00;  //R0 LOW
	pPortDOutReg->pin_1  = 0X00;  //R1 LOW
	pPortDOutReg->pin_2  = 0X00;  //R2 LOW
	pPortDOutReg->pin_3  = 0X00;  //R3 LOW
}
