/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdio.h>
#include <stdint.h>

void UsageFault_Handler_c(uint32_t *pBaseStackFrame);

int main(void)
{
    //1. Enable all configurable fault exceptions like usage fault, mem manage fault and bus fault.
	uint32_t *pSHCSR = (uint32_t*)0xE000ED24;
	*pSHCSR |= (1<<16); //Activate mem manage fault.
	*pSHCSR |= (1<<17); //Activate bus fault.
	*pSHCSR |= (1<<18); //Activate usage fault.

	//2. Lets force the processor to execute some undefined instruction.
	uint32_t *pSRAM = (uint32_t*)0x20010000;
	*pSRAM = 0xFFFFFFFF;
	void (*some_address)(void);
	some_address = (void*)0x20010001; //Bit 0 is changed to 1 due to T-bit. Instead of 0x20010000 we write 0x20010001.
	some_address();

	//4. Analyze the fault.

	for(;;);
}

//3. Implement the fault handlers.

void HardFault_Handler(void)
{
	printf("Fault : HardFault\n");
	while(1);
}

void MemManage_Handler(void)
{
	printf("Fault : MemManage\n");
	while(1);
}

void BusFault_Handler(void)
{
	printf("Fault : BusFault\n");
	while(1);
}

__attribute__((naked)) void	UsageFault_Handler()
{
	/*Here we extract the value of the MSP which happens to be the base address
	* of the stack frame(thread mode). Which got saved during during the exception entry
	  from thread mode to handler mode.*/
	__asm volatile("MRS r0,MSP");

	__asm volatile("B UsageFault_Handler_c");  //Calling the function through 'Branch(B)' instruction.

 /*R0 value will be automatically passed as the 1st argument of the calling function. According to AAPCS. Here calling function is
   UsageFault_Handler_c(uint32_t *pBaseStackFrame) and R0 value is copied to *pBaseStackFrame.
 */
}

void UsageFault_Handler_c(uint32_t *pBaseStackFrame)
{
	printf("Fault : UsageFault\n");

	//Checking the details of the Usage Fault by exploring the UFSR(Usage Fault Status Register)
	uint16_t *pUFSR = (uint16_t*)0xE000ED2A;
	printf("UFSR = %X\n",( (*pUFSR) & 0xFFFF) );

	//Printing the value of the MSP as base of the stack frame.
	printf("MSP = %p\n",pBaseStackFrame);

	//Printing out Stack Frame contents.
	printf("Value of R0   = %lX\n",pBaseStackFrame[0]);
	printf("Value of R1   = %lX\n",pBaseStackFrame[1]);
	printf("Value of R2   = %lX\n",pBaseStackFrame[2]);
	printf("Value of R3   = %lX\n",pBaseStackFrame[3]);
	printf("Value of R12  = %lX\n",pBaseStackFrame[4]);
	printf("Value of LR   = %lX\n",pBaseStackFrame[5]);
	printf("Value of PC   = %lX\n",pBaseStackFrame[6]);
	printf("Value of XPSR = %lX\n",pBaseStackFrame[7]);

	while(1);
}
