/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	uint32_t *pClkctrlReg   =(uint32_t*) 0x40023830;
	uint32_t *pPortDModeReg =(uint32_t*) 0x40020C00;
	uint32_t *pPortDOutReg  =(uint32_t*) 0x40020C14;

	//1. Enable the clock of GPIOD peripheral in the AHB1ENR.
	*pClkctrlReg |= (0x1<<3);

	//2. Configure the mode for the IO pin as OUTPUT.
	*pPortDModeReg &= ~(0x3<<24); //Clearing the 24th and 25th bit.
	*pPortDModeReg |= (0x1<<24);  //Setting the 24th bit.

	//Creating a super loop(infinite loop).
	while(1){

	//3. Set 12th bit of the output data register to make I/O pin 12 as HIGH.
	*pPortDOutReg |= (0x1<<12);

	//Introduce small human observable delay.
	//This loop execute for 10k times.
	for(uint32_t i = 0; i <300000; i++);

	//4. Clear 12th bit of the output data register to make I/O pin 12 as LOW.
	*pPortDOutReg &= ~(0x1<<12);

	for(uint32_t i = 0; i <300000; i++);
	}
}
