/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"


int main(void){

    RCC_AHB1ENR_t volatile *const pClkCtrlReg   = ADDR_REG_AHB1ENR;
    GPIOx_MODER_t volatile *const pPortDModeReg = ADDR_REG_GPIO_MODE;
    GPIOx_ODR_t   volatile *const pPortDOutReg  = ADDR_REG_GPIO_OD;

//Enabling the clock for GPIOD peripheral
    pClkCtrlReg->gpioD_en = CLOCK_ENABLE;

//Configure the mode of the IO pin as output
    pPortDModeReg->pin_12 = MODE_CONF_OUTPUT;

    while(1){
    //Set 12th bit of the output data register to make IO pin 12 as HIGH
        pPortDOutReg->pin_12 = PIN_STATE_HIGH;
    //Introduce small human observable delay
        for(uint32_t i = 0; i < DELAY_COUNT; i++);
    //Reset 12th bit of the output data register to make IO pin 12 as LOW
        pPortDOutReg->pin_12 = PIN_STATE_LOW;

        for(uint32_t i = 0; i < DELAY_COUNT; i++);
    }
}
