/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>


//delay function for button debouncing
void delay(void){

	for(uint32_t i = 0 ; i < 300000 ; i++);

}

int main(void)
{
    //Peripheral register addresses.
	uint32_t volatile *const pGPIODModeReg   = (uint32_t*) (0x40020C00 + 0x00);
	uint32_t volatile *const pInPutDataReg   = (uint32_t*) (0x40020C00 + 0x10);
	uint32_t volatile *const pOutPutDataReg  = (uint32_t*) (0x40020C00 + 0x14);
	uint32_t volatile *const pClockCtrlReg   = (uint32_t*) (0x40023800 + 0x30);
	uint32_t volatile *const pPullupDownReg  = (uint32_t*) (0x40020C00 + 0x0C);

	//1. Enable the clock of GPIOD peripheral.
	*pClockCtrlReg |= (0x01 << 3);

	//2. Configure PD0, PD1, PD2, PD3 as output (Rows).
	*pGPIODModeReg &= ~(0xFF); //clear
	*pGPIODModeReg |=  (0x55);  //set

	//3. Configure PD8, PD9, PD10, PD11 as input (Column).
	*pGPIODModeReg &= ~(0xFF << 16);

	//4. Enable internal Pull-UP resistors for PD8, PD9, PD10, PD11.
	*pPullupDownReg &= ~(0xFF << 16);
	*pPullupDownReg |=  (0x55 << 16);

	while(1){

		//Make all rows HIGH.
		*pOutPutDataReg |= (0x0F);

		//make R1 LOW(PD0).
		*pOutPutDataReg &= ~(0x01 << 0);

		//Scan the columns.

		//Check C1(PD8) low or high.
		if(!(*pInPutDataReg & (0x01 << 8))){
			//Key is pressed.
			delay();
			printf("1\n");
		}

		//Check C2(PD9) low or high.
		if(!(*pInPutDataReg & (0x01 << 9))){
			//Key is pressed.
			delay();
			printf("2\n");
		}

		//Check C3(PD10) low or high.
		if(!(*pInPutDataReg & (0x01 << 10))){
			//Key is pressed.
			delay();
			printf("3\n");
		}

		//Check C4(PD11) low or high.
		if(!(*pInPutDataReg & (0x01 << 11))){
			//Key is pressed.
			delay();
			printf("A\n");
		}


		//Make all rows HIGH.
		*pOutPutDataReg |= (0x0F);

		//make R2 LOW(PD1).
		*pOutPutDataReg &= ~(0x01 << 1);

		//Scan the columns.

		//Check C1(PD8) low or high.
		if(!(*pInPutDataReg & (0x01 << 8))){
			//Key is pressed.
			delay();
			printf("4\n");
		}

		//Check C2(PD9) low or high.
		if(!(*pInPutDataReg & (0x01 << 9))){
			//Key is pressed.
			delay();
			printf("5\n");
		}

		//Check C3(PD10) low or high.
		if(!(*pInPutDataReg & (0x01 << 10))){
			//Key is pressed.
			delay();
			printf("6\n");
		}

		//Check C4(PD11) low or high.
		if(!(*pInPutDataReg & (0x01 << 11))){
			//Key is pressed.
			delay();
			printf("B\n");
		}


		//Make all rows HIGH.
		*pOutPutDataReg |= (0x0F);

		//make R3 LOW(PD2).
		*pOutPutDataReg &= ~(0x01 << 2);


		//Scan the columns.

		//Check C1(PD8) low or high.
		if(!(*pInPutDataReg & (0x01 << 8))){
			//Key is pressed.
			delay();
			printf("7\n");
		}

		//Check C2(PD9) low or high.
		if(!(*pInPutDataReg & (0x01 << 9))){
			//Key is pressed.
			delay();
			printf("8\n");
		}

		//Check C3(PD10) low or high.
		if(!(*pInPutDataReg & (0x01 << 10))){
			//Key is pressed.
			delay();
			printf("9\n");
		}

		//Check C4(PD11) low or high.
		if(!(*pInPutDataReg & (0x01 << 11))){
			//Key is pressed.
			delay();
			printf("C\n");
		}


		//Make all rows HIGH.
		*pOutPutDataReg |= (0x0F);

		//make R4 LOW(PD3).
		*pOutPutDataReg &= ~(0x01 << 3);

		//Scan the columns.

		//Check C1(PD8) low or high.
		if(!(*pInPutDataReg & (0x01 << 8))){
			//Key is pressed.
			delay();
			printf("*\n");
		}

		//Check C2(PD9) low or high.
		if(!(*pInPutDataReg & (0x01 << 9))){
			//Key is pressed.
			delay();
			printf("0\n");
		}

		//Check C3(PD10) low or high.
		if(!(*pInPutDataReg & (0x01 << 10))){
			//Key is pressed.
			delay();
			printf("#\n");
		}

		//Check C4(PD11) low or high.
		if(!(*pInPutDataReg & (0x01 << 11))){
			//Key is pressed.
			delay();
			printf("D\n");
		}

	}//While End

}
