/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2020 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdio.h>


int main(void)
{
    char msg1[] = "Hello how are you?"; //"Hello how are you?" is stored in flash memory but msg1 is created in STACK section, so a copy of the whole string is created in the STACK. It is modifiable.
    char *msg2  = "Hello how are you?"; // "Hello how are you?" is stored in flash memory and msg2 is in STACK section, pointing to flash address. Can't modifiable.

    msg1[0] = 'C';

    printf("The message is : %s\n", msg1);
    printf("The message is : %s\n", msg2);
    printf("Address of 'msg1' variable =%p\n", &msg1);
    printf("Address of 'msg2' variable =%p\n", &msg2);
    printf("Value of 'msg1' variable   =%p\n", msg1);
    printf("Value of 'msg2' variable   =%p\n", msg2);


	for(;;);
}
